plugins {
    id 'java'
}

group = 'app.ezclient'
version = '1.5.1'

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    // Only compile against the Fabric Loader API
    compileOnly "net.fabricmc:fabric-loader:0.16.5"
    // We also need LWJGL for the GLFW stuff during compile time
    compileOnly "org.lwjgl:lwjgl-glfw:3.3.3"
    compileOnly "org.lwjgl:lwjgl:3.3.3"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

jar {
    archiveBaseName.set('EzClient-Lite')
}
