"""Generate the launcher and in-game display dictionaries from reviewed DE/EN pairs."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def pairs():
    result = {}
    lines = [line for path in sorted((ROOT / "localization").glob("*.tsv"))
             for line in path.read_text(encoding="utf-8").splitlines()]
    for line in lines:
        if not line or line.startswith("#"):
            continue
        de, en = line.split("\t", 1)
        for escape, value in ((r"\n", "\n"), (r'\"', '"')):
            de, en = de.replace(escape, value), en.replace(escape, value)
        if de in result and result[de] != en:
            raise ValueError(f"Conflicting translation: {de}")
        result[de] = en
    return result


def generate():
    translations = pairs()
    js = '.pragma library\n// Generated by tools/update_display_translations.py.\nvar translations = '
    js += json.dumps(translations, ensure_ascii=False, indent=2) + ';\n'
    js += 'var reverse = {};\nObject.keys(translations).forEach(function(key) { reverse[translations[key]] = key; });\n'
    js += 'function text(value, language) {\n    var table = language === "en" ? translations : reverse;\n    return Object.prototype.hasOwnProperty.call(table, value) ? table[value] : value;\n}\n'
    (ROOT / "ui/DisplayText.js").write_text(js, encoding="utf-8")
    language_dir = ROOT / "client_mod/src/main/resources/assets/ezclient/lang"
    for language in ("de_de", "en_us"):
        path = language_dir / f"{language}.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        data = {key: value for key, value in data.items() if not key.startswith("ezclient.ui.")}
        for de, en in translations.items():
            key = "ezclient.ui." + hashlib.sha1(de.encode("utf-8")).hexdigest()[:16]
            data[key] = de if language == "de_de" else en
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {len(translations)} reviewed display translations")


if __name__ == "__main__":
    generate()
